// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// HashStorage is an autogenerated mock type for the hashStorage type
type HashStorage struct {
	mock.Mock
}

type HashStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *HashStorage) EXPECT() *HashStorage_Expecter {
	return &HashStorage_Expecter{mock: &_m.Mock}
}

// AddUnique provides a mock function with given fields: ctx, key, value
func (_m *HashStorage) AddUnique(ctx context.Context, key string, value string) error {
	ret := _m.Called(ctx, key, value)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HashStorage_AddUnique_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUnique'
type HashStorage_AddUnique_Call struct {
	*mock.Call
}

// AddUnique is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value string
func (_e *HashStorage_Expecter) AddUnique(ctx interface{}, key interface{}, value interface{}) *HashStorage_AddUnique_Call {
	return &HashStorage_AddUnique_Call{Call: _e.mock.On("AddUnique", ctx, key, value)}
}

func (_c *HashStorage_AddUnique_Call) Run(run func(ctx context.Context, key string, value string)) *HashStorage_AddUnique_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *HashStorage_AddUnique_Call) Return(_a0 error) *HashStorage_AddUnique_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HashStorage_AddUnique_Call) RunAndReturn(run func(context.Context, string, string) error) *HashStorage_AddUnique_Call {
	_c.Call.Return(run)
	return _c
}

// NewHashStorage creates a new instance of HashStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHashStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *HashStorage {
	mock := &HashStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
