name: Go

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:

  build-and-test:
    strategy:
      matrix:
        go: [ 1.21 ]
        os: [ macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build Server
        run: go build -v cmd/server/*.go

      - name: Build Client
        run: go build -v cmd/client/*.go

      - name: Test
        run: go test -v ./...